name: Kubernetes Deployment

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v2
        with:
          docker-version: 20.10.7

      - name: Build Docker Image
        run: docker build -t julien94800/image-front:latest .
        working-directory: ./path/to/your/app

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: docker push julien94800/image-front:latest

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: kubectl apply -f ./path/to/your/kubernetes-manifest.yaml -n devops
